---
- hosts: roxanne
  sudo: true
  gather_facts: no

  pre_tasks:
    - name: install python if it is not there already
      raw: apt-get update && apt-get -y install python
    - name: Gathering facts
      setup:

  tasks:
    - name: install some packages
      apt: "name={{ item }} state=present"
      with_items:
        - irssi
    - name: configure shorewall to allow incoming irc-server connections
      lineinfile: "dest=/etc/shorewall/rules line=\"ACCEPT:info ext:{{item}} fw tcp 7029\" state=present create=yes"
      with_items:
          - 188.226.251.4     # melissa
          - 46.101.57.19      # barbie
          - 104.236.167.230   # roxanne
          - 104.236.167.230   # roxanne
          - 72.20.33.91       # irc1.us
          - 174.37.216.199    # irc2.us
          # - 81.169.186.131    # irc3.de
          - 5.9.146.202       # irc4.de
      notify:
        - restart shorewall
      tags:
        - firewall

  roles:
    - generic
    - shorewall
    - shorewall6
    - { 
        role: inspircd, 
        confdir: "inspircd-config/",
        secretdir: "inspircd-secrets/"
      }

