---
- hosts: all
  sudo: true

  roles:
    - generic
    - shorewall
    - role: dockerinstance
      instances:
        - { 
            name: boobiesbot, 
            dockerfile: "https://raw.githubusercontent.com/StevenVanAcker/OverTheWire-boobiesbot/master/Dockerfile"
          }
        #- { 
        #    name: hintbot, 
        #    dockerfile: "https://raw.githubusercontent.com/StevenVanAcker/OverTheWire-hintbot/master/Dockerfile"
        #  }
    - { 
        role: inspircd, 
        confdir: "inspircd-config/"
      }

