---
- hosts: all
  sudo: true

  tasks:
    - name: install some packages
      apt: "name={{ item }} state=present"
      with_items:
        - irssi

  roles:
    - generic
    - shorewall
    - { 
        role: inspircd, 
        confdir: "inspircd-config/",
        secretdir: "inspircd-secrets/"
      }

