---
- hosts: all
  sudo: true

  tasks:
    - name: install some packages
      apt: "name={{ item }} state=present"
      with_items:
        - irssi
        - mongodb-server

    - name: configure mongodb
      lineinfile: dest=/etc/mongodb.conf regexp="^bind_ip" line="bind_ip = 0.0.0.0" state=present create=yes
      register: mongodbconf

    - name: restarting mongodb if needed
      service: name=mongodb state=restarted
      when: mongodbconf.changed

  roles:
    - generic
    - shorewall
    - { 
        role: inspircd, 
        confdir: "inspircd-config/",
        secretdir: "inspircd-secrets/"
      }
    - role: dockerinstance
      instances:
        - {
            name: boobiesbot,
            uid: 5000,
            dockerfile: "https://raw.githubusercontent.com/StevenVanAcker/OverTheWire-boobiesbot/master/Dockerfile"
          }

