---
- hosts: all
  sudo: true

  tasks:
    - name: install some packages
      apt: "name={{ item }} state=present"
      with_items:
        - irssi

  roles:
    - generic
    - shorewall
    - { 
        role: inspircd, 
        confdir: "inspircd-config/",
        secretdir: "inspircd-secrets/"
      }
    - role: dockerinstance
      instances:
        - {
            name: boobiesbot,
            uid: 5000,
            dockerfile: "https://raw.githubusercontent.com/StevenVanAcker/OverTheWire-boobiesbot/master/Dockerfile"
          }

