  - name: check if shorewall is installed
    command: dpkg -s shorewall
    register: shorewallinstalled
    failed_when: false
    changed_when: false
    tags:
        - firewall

  - name: configure shorewall
    lineinfile: "dest={{ item.filename }} line=\"{{ item.line }}\" state=present create=yes"
    with_items:
        - { filename: "/etc/shorewall/rules", line: "ACCEPT:info ext fw tcp 6666,6667,6697" }
    when: shorewallinstalled is defined and shorewallinstalled.rc == 0
    notify:
      - restart shorewall
    register: shorewallconfig
    tags:
        - firewall

  - name: force reload shorewall
    shell: "shorewall check && shorewall restart"
    when: shorewallconfig.changed
    tags:
        - firewall

  - name: check if shorewall6 is installed
    command: dpkg -s shorewall6
    register: shorewall6installed
    failed_when: false
    changed_when: false
    tags:
        - firewall

  - name: configure shorewall6
    lineinfile: "dest={{ item.filename }} line=\"{{ item.line }}\" state=present create=yes"
    with_items:
        - { filename: "/etc/shorewall6/rules", line: "ACCEPT:info ext fw tcp 6666,6667,6697" }
    when: shorewall6installed is defined and shorewall6installed.rc == 0
    notify:
      - restart shorewall6
    register: shorewall6config
    tags:
        - firewall

  - name: force reload shorewall6
    shell: "shorewall6 check && shorewall6 restart"
    when: shorewall6config.changed
    tags:
        - firewall
