  - include: firewall.yaml

  - name: install packages
    apt: "name={{ item }} state=present"
    with_items:
        - gnutls-bin

  - name: install inspircd build dependencies
    command: apt-get -y build-dep inspircd
    register: cmdres
    changed_when: "cmdres|changed and '0 upgraded, 0 newly installed, 0 to remove' not in cmdres.stdout"

  - name: create /opt/inspircd
    file: path=/opt/inspircd state=directory mode=0750 owner=irc group=root

  - name: get inspircd code from github
    git: repo=https://github.com/inspircd/inspircd.git
         dest=/usr/src/inspircd
         version=v2.0.18
    register: gitclone

  - name: was there a previous compile that failed?
    stat: path=/opt/inspircd/.needsupdate
    register: needsupdate

  - name: compile and build inspircd
    command: "{{ item }} chdir=/usr/src/inspircd"
    with_items:
        - "touch /opt/inspircd/.needsupdate"
        - "./configure --enable-extras=m_ssl_gnutls.cpp"
        - "./configure --prefix=/opt/inspircd --uid=irc --gid=irc"
        - "make -j{{ansible_processor_vcpus}}"
        - "make INSTUID=irc install"
        - "rm -f /opt/inspircd/.needsupdate"
    when: gitclone.changed or needsupdate.stat.exists

  - name: create symlink to init-script
    file: path=/etc/init.d/inspircd src=/opt/inspircd/inspircd state=link

  - name: copy config files
    copy: "src={{confdir}} dest=/opt/inspircd/conf/ owner=irc group=irc mode=0640"
    register: copiedconfig

  - name: rehash inspircd config if needed
    command: /etc/init.d/inspircd rehash
    when: copiedconfig.changed

  - name: have the DH params been generated?
    stat: path=/opt/inspircd/conf/ssl/dhparams.pem
    register: dhparams

  - name: generate DH params if needed
    command: certtool --generate-dh-params --sec-param high --outfile /opt/inspircd/conf/ssl/dhparams.pem
    when: not dhparams.stat.exists

  - name: make sure inspircd starts on boot
    service: name=inspircd enabled=yes

  - name: is the hostname already configured in inspircd?
    stat: path=/opt/inspircd/conf/servers/config-myname.conf
    register: nameconfiged

  - name: configuring own hostname if needed
    script: config-myname.sh
    when: not nameconfiged.stat.exists

  - name: starting inspircd
    service: name=inspircd state=started

