- name: install some apt packages
  apt: "name={{ item }} state=present"
  with_items:
    - openvpn
    - easy-rsa

- name: copy openvpn files
  copy: src=vpnfiles/{{item}} dest=/etc/openvpn/{{item}} mode=0400
  register: copyvpnfiles
  with_items:
    - ca.crt
    - server.key
    - server.conf
    - server.crt
    - dh2048.pem

- name: fix openvpn defaults for init script
  lineinfile: dest=/etc/default/openvpn regexp="^AUTOSTART=" line="AUTOSTART=\"all\"" state=present create=yes
  register: ovpninit

- name: reload systemctl if it exists
  command: systemctl daemon-reload
  failed_when: false

- name: configure shorewall
  lineinfile: "dest={{ item.filename }} line=\"{{ item.line }}\" state=present create=yes"
  with_items:
      - { filename: "/etc/shorewall/interfaces", line: "int tun0" }
      - { filename: "/etc/shorewall/zones", line: "int ipv4" }
      - { filename: "/etc/shorewall/masq", line: "eth0    192.168.45.0/24" }
      - { filename: "/etc/shorewall/rules", line: "ACCEPT:info ext fw tcp 1194" }
      - { filename: "/etc/shorewall/rules", line: "ACCEPT:info fw int all" }
      - { filename: "/etc/shorewall/rules", line: "ACCEPT:info int ext all" }
  register: shorewallconfig
  tags:
      - firewall

- name: set ip forwarding
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes
